### ISSUE TITLE
[Epic][Link previews][QA] Implement the new link preview design

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#130]
### Description

- Figma: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?type=design&mode=design&t=6rUQVD7CqUEFVkCO-0

- Dev issues:
UI epic https://github.com/status-im/status-desktop/issues/12178

### Tasks

- [x] Create e2e happy paths based on Figma
- https://ethstatus.testrail.net/index.php?/suites/view/5308&group_id=51501
- [x] Create Negative scenarios
- [x] Execute happy paths, minimum
- [x] Create automation tasks in backlog
- https://github.com/status-im/desktop-qa-automation/issues/187
- https://github.com/status-im/desktop-qa-automation/issues/281

### Test summary

Description of tests and results.
