### ISSUE TITLE
[EPIC][Wallet Providers][QA][Sepolia support]

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#161]
### Description: 

- support sepolia network (as a replacement for Goerli)

- Dev issues: 
https://github.com/status-im/status-desktop/issues/12322 - SEPOLIA (L1)
https://github.com/status-im/status-desktop/issues/12401 - ARBITRUM SEPOLIA (L2)
https://github.com/status-im/status-desktop/issues/12404 - allow deployer on Sepolia
https://github.com/status-im/status-desktop/issues/12470 - bridge
https://github.com/status-im/status-go/pull/4736 - ens / stickers support

### Tasks

- [x] Create e2e happy paths based on Figma. 

_So basically, there is no figma for that, however the switching to Sepolia lives under Advanced section for now, until we fully switch. Sepolia is supported by Infura and Pokt. Currently, we have L1 and Arbitrum Sepolia in master, and there is no yet Optimism Sepolia at all._

**UPD:** sepolia optimism https://github.com/status-im/status-desktop/pull/13325

**NOTE:** there is no any bridge for Sepolia, so sending from L1 to L2 is not possible being on this network

- [ ]  Create Negative scenarios
- [ ]  Execute happy paths, minimum
- [ ]  Create automation tasks in backlog

### Test summary

- [ ] Send ETH from wallet - send
- [ ] Send ERC 20 tokens from wallet - send (fake tokens)
- [ ] Send SNT test token on Sepolia (requires a contract deployment, this is to do for Pascal)
- [ ] Buy ENS name on Sepolia (requires a contract deployment, this is to do for Pascal)
- [ ] Buy stickers on Sepolia (requires a contract deployment, this is to do for Pascal)
- [ ] Send ERC 721 (nfts) from wallet - send
- [ ] Mint owner token , token master on sepolia
- [ ] Airdrop on sepolia
- [ ] Remote destruct tokens on sepolia
- [ ] Asset view should show correct balances when being on Sepolia
- [ ] Activity view should show correct values, and redirect to correct explorer (sepolia etherscan)

### Faucets
- fake DAI (erc 20) https://sepolia.etherscan.io/address/0x3e622317f8c93f7328350cf0b56d9ed4c620c5d6#writeContract
- sepolia (l1) faucet https://sepoliafaucet.com/

**Comment by anastasiyaig** [comment]
Okay, so I am moving this to 0.16 because there is still a dev task to complete
