### ISSUE TITLE
[EPIC][Desktop New Wallet Settings] New designs for edit network settings

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#181]
### Description:

Implement missing designs for edit network

**Dev tasks:**

- https://github.com/status-im/status-desktop/issues/11751
- Figma: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=15248-327743&mode=dev

### Tasks

- [x] Create e2e happy paths based on Figma
https://ethstatus.testrail.net/index.php?/cases/view/703515 was updated
- [ ]  Create Negative scenarios
added a todo here https://github.com/status-im/desktop-qa-automation/issues/265
- [x]  Execute happy paths, minimum
- [x]  Create automation tasks in backlog

I have created PR with the test itself (no task) https://github.com/status-im/desktop-qa-automation/pull/172

**Comment by anastasiyaig** [comment]
I am closing this Epic as done. Editing network works and tests daily with autotests. I will cover negative scenarios later and will automate them (low priority now)
