### ISSUE TITLE
[EPIC][Desktop Watch Only Visibility] Include watch only per account

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#182]
### Description:

control per account which watch address is being displayed

**Dev tasks:**
- https://github.com/status-im/status-desktop/issues/12305
- figma https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=19218-313442&mode=design&t=HnNmumCrgH8Vl23C-0

**Tasks**
- [x]  Create e2e happy paths based on Figma
- https://ethstatus.testrail.net/index.php?/cases/view/703508
- [x]  Create Negative scenarios
- https://github.com/status-im/desktop-qa-automation/issues/289
- [x]  Execute happy paths, minimum
- [x]  Create automation tasks in backlog
- https://github.com/status-im/desktop-qa-automation/issues/280

**Bugs**:

- [x] https://github.com/status-im/status-desktop/issues/12579
- [ ] https://github.com/status-im/status-desktop/issues/12581
- [x] https://github.com/status-im/status-desktop/issues/12582
- [ ] https://github.com/status-im/status-desktop/issues/12623
