### ISSUE TITLE
[EPIC][Web/Deep links][QA] Open status.app links

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#184]
### Dev issues
Epic: https://github.com/status-im/status-desktop/issues/12245

### Tasks
- [ ] Create e2e happy paths based on Figma
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog
- [ ] 

### Test summary
Description of tests and results.

**Comment by anastasiyaig** [comment]
Trying to figure out what is going on with dev side of that
