### ISSUE TITLE
[EPIC][Wallet][QA] New Settings

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#248]
QA for https://github.com/status-im/status-desktop/issues/11130

### Description

New settings redesign for wallet in multiple areas

**Figma:** https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?type=design&node-id=2499-150211&t=9KNNvAQQjs6WwKuC-0

**Tasks:**

- [x] create happy path in test rail

**Add account:**
https://ethstatus.testrail.net/index.php?/cases/view/703598 I covered only 1 scenario because the functionality is that simple, it is just clicking button and calling the same modal used in general wallet. We have more tests when doing this from main wallet screen

**Account list:** it will be covered in other tests as this is just a component being redesigned

**Watch only account toggle** This has been redesigned to remove and implemented per account

**Networks**
https://ethstatus.testrail.net/index.php?/cases/view/703515
https://ethstatus.testrail.net/index.php?/cases/view/703622
https://ethstatus.testrail.net/index.php?/cases/view/703621
https://ethstatus.testrail.net/index.php?/cases/view/703505

**Account Order**
https://ethstatus.testrail.net/index.php?/cases/view/703415
https://ethstatus.testrail.net/index.php?/cases/view/703416

**Account Interaction**

https://ethstatus.testrail.net/index.php?/cases/view/703420
https://ethstatus.testrail.net/index.php?/cases/view/703507
https://ethstatus.testrail.net/index.php?/cases/view/704603
https://ethstatus.testrail.net/index.php?/cases/view/704604

**Preferred networks and account view interactions**
https://ethstatus.testrail.net/index.php?/cases/view/704433
https://ethstatus.testrail.net/index.php?/cases/view/704454
https://ethstatus.testrail.net/index.php?/cases/view/704605

**Watch only toggle**
https://ethstatus.testrail.net/index.php?/cases/view/703508

- [x] create negative scenarios
Added a todo https://github.com/status-im/desktop-qa-automation/issues/300
- [x] execute happy path, minimum
- [x] add tasks for automation in backlog
Add account, delete account, edit account, toggle watch-only are already automated

**Bugs:**
