### ISSUE TITLE
Automation Epic

### ISSUE THREAD

**Issue by iurimatias** [status-im/desktop-qa-automation#4]
Onboarding
- [x] https://github.com/status-im/status-desktop/issues/6435 (note: needs confirmation)
- [x] [Can login with correct password](https://github.com/status-im/status-desktop/pull/6540/files#diff-6f9bf2b681e8b71c5483051a02e8d1d881097a0654b16f469ccf7dedc27765b8R207) (note: needs confirmation)
- [x] [Can relogin after restart](https://github.com/status-im/status-desktop/pull/6540/files#diff-6f9bf2b681e8b71c5483051a02e8d1d881097a0654b16f469ccf7dedc27765b8R207) (note: needs confirmation)
- [x] [Import 12, 18 and 24 seed phrases](https://github.com/status-im/status-desktop/pull/6399) (note: needs confirmation)
  - [x] a seed phrase that fails the checksum should results in an error
- [ ] [After login the status should be online](https://github.com/status-im/status-desktop/issues/6854)

Chat
- [x] [Join a public channel and send a message](https://github.com/status-im/status-desktop/pull/6540) (note: needs confirmation)
- [x] status-im/status-desktop#6670
- [x] status-im/status-desktop#6671
- [x] status-im/status-desktop#6876
- [x] status-im/status-desktop#6757
- [x] status-im/status-desktop#6758
- [x] status-im/status-desktop#6877
- [x] status-im/status-desktop#6878
- [x] status-im/status-desktop#6879
- [x] status-im/status-desktop#6880
- [x] status-im/status-desktop#6881
- [x] status-im/status-desktop#6882
- [x] status-im/status-desktop#6883
- [x] status-im/status-desktop#6884
- [x] status-im/status-desktop#6885
- [x] status-im/status-desktop#6962

Group Chat
- [x] https://github.com/status-im/status-desktop/issues/6444
- [x] status-im/desktop-qa-automation#12
- [x] status-im/status-desktop#7061
- [x] status-im/desktop-qa-automation#13
- [x] status-im/desktop-qa-automation#14
- [x] status-im/status-desktop#7064
- [x] status-im/status-desktop#7065
- [x] status-im/desktop-qa-automation#15

Communities
- [x] https://github.com/status-im/status-desktop/issues/6445
- [x] status-im/status-desktop#6756
- [x] status-im/status-desktop#6886
- [x] https://github.com/status-im/status-desktop/issues/6533
- [x] https://github.com/status-im/status-desktop/issues/6534
- [x] status-im/status-desktop#6887
- [x] status-im/status-desktop#6751
- [x] status-im/status-desktop#6752
- [x] status-im/status-desktop#6888
- [x] status-im/status-desktop#6750
- [x] status-im/status-desktop#6889
- [x] status-im/status-desktop#6890
- [x] status-im/status-desktop#6891
- [x] status-im/status-desktop#6892
- [x] status-im/desktop-qa-automation#25
- [x] status-im/status-desktop#6894
- [x] status-im/status-desktop#6895

Wallet
- https://github.com/status-im/status-desktop/issues/6507
  - [x] status-im/status-desktop#6754
  - [x] [Generate new account](https://github.com/status-im/status-desktop/pull/6502)
  - [x] Can generate an account with a custom derivation path
- Account management
  - [x] status-im/status-desktop#6761
  - [x] status-im/status-desktop#6817
  - [x] status-im/status-desktop#6819
  - [x] status-im/status-desktop#6898
  - [x] status-im/status-desktop#6896
  - Saved Addresses
    - [x] [Can add an address to Saved addresses](https://github.com/status-im/status-desktop/issues/6761)
    - [x] status-im/desktop-qa-automation#26
    - [x] status-im/status-desktop#6818
    - [x] Can bookmark a saved address
- Transactions
  - [x] [Basic send transaction](https://github.com/status-im/status-desktop/pull/6581)
  - [x] status-im/desktop-qa-automation#26
- [x] [Wallet](https://github.com/status-im/status-desktop/issues/7528)
  - User adds a watch only account
  - User generates a new account from wallet
  - User imports a private key
  - User imports a seed phrase
  - User deletes a generated account
  - Can see collectibles for an account
  - User can edit the default wallet account
  - User can toggle network and see balances

Settings
- [x] status-im/status-desktop#6900
- [x] status-im/status-desktop#6901
- [x] status-im/status-desktop#6902
- [x] status-im/status-desktop#6903
- [x] status-im/status-desktop#6904

General
- [x] status-im/status-desktop#6905
- [ ] status-im/desktop-qa-automation#20

Activity Center
- [ ] Can see replies and mentions in activity center
- [ ] Can jump to a message from the activity center
- [ ] Can mark an activity center notification as read

CI integration
- [x] https://github.com/status-im/status-desktop/issues/5960
