### ISSUE TITLE
[QA EPIC] UI flows for sending owner token

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#402]
Desktop issue 1: https://github.com/status-im/status-desktop/issues/12087
Desktop issue 2: https://github.com/status-im/status-desktop/issues/11370

### Tasks

- [ ] Create e2e happy paths based on Figma -> [TestRail](https://ethstatus.testrail.net/index.php?/suites/view/5308&group_by=cases:section_id&group_id=51498&group_order=asc&display_deleted_cases=0)
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog

### Test summary

Description of tests and results

**Comment by anastasiyaig** [comment]
i am taking over this. All the tasks related to implementation are completed, i will simply retest the whole thing in master

**Comment by glitchminer** [comment]
Migrated scenarios from spreadsheet used in previous run to TR in preparation for regression cycle.
