### ISSUE TITLE
[QA EPIC] Wallet - Token management

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#405]
Desktop issues:
https://github.com/status-im/status-desktop/issues/12306

### Tasks

- [ ] Create e2e happy paths based on Figma - [TestRail](https://ethstatus.testrail.net/index.php?/suites/view/5308&group_by=cases:section_id&group_id=51537)
- [ ] Create Negative scenarios
- [ ] Execute happy paths, minimum
- [ ] Create automation tasks in backlog

### Test summary

Description of tests and results

**Comment by anastasiyaig** [comment]
@lukaszso do you need any help with that?

**Comment by lukaszso** [comment]
@anastasiyaig the only thing left to cover in testrail is grouping. I'm on it, will be done today.

**Comment by lukaszso** [comment]
Closing this one. Other testing efforts will be carried out within RC test runs.
