### ISSUE TITLE
[EPIC] Saved Addresses - New Design

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#425]
Test efforts for https://github.com/status-im/status-desktop/issues/13087

- [x] Fix existing automated tests https://github.com/status-im/desktop-qa-automation/issues/427: https://github.com/status-im/desktop-qa-automation/issues/427
- [ ] Review test rail and create scenarios based on new designs
        - https://ethstatus.testrail.net/index.php?/cases/view/704620
- [x] Create tasks for automation in backlog
        - https://github.com/status-im/desktop-qa-automation/issues/430
        - https://github.com/status-im/desktop-qa-automation/issues/452

**Comment by anastasiyaig** [comment]
no qa epics anymore
